### ISSUE TITLE
id was called incorrectly

### ISSUE THREAD

**Issue by lawkwok** [wpovernight/woocommerce-pdf-invoices-packing-slips#28] opened 2017-06-21 17:13 UTC
I am using the Simple template and create an invoice or packing slip this appears on the error log:

> id was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('wp_ajax_generate_wpo_wcpdf'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WooCommerce_PDF_Invoices_Export->generate_pdf_ajax, WooCommerce_PDF_Invoices_Export->get_pdf, WooCommerce_PDF_Invoices_Export->generate_pdf, WooCommerce_PDF_Invoices_Export->process_template, do_action('wpo_wcpdf_process_template_order'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WOOCS->wpo_wcpdf_process_template_order, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: https://example.com/wp-admin/edit.php?post_status=wc-on-hold&post_type=shop_order

**Comment by Spreeuw** [comment] 2017-06-21 19:46
Seems to be caused by WOOCS = WooCommerce Currency Switcher

**Comment by Spreeuw** [comment] 2017-06-26 18:23
@lawkwok can you confirm that disabling WooCommerce Currency Switcher fixes this issue?

**Comment by Spreeuw** [comment] 2017-07-04 13:03
closing for now...

**Closed by Spreeuw** 2017-07-04 13:03 UTC
