### ISSUE TITLE
Generated invoice for failed orders - very rarelly

### ISSUE THREAD

**Issue by maralik** [wpovernight/woocommerce-pdf-invoices-packing-slips#42] opened 2017-12-06 14:11 UTC
Hello,

very rarelly we get generated invoice for order which was not paid and failed - see the attachment. It happens for one of ~30 orders which failed, but it's quite huge problem for us, because it breaks our invoice numbers line. Any idea what is the cause? For payments we use Braintree For WooCommerce Pro made by PaymentPlugins.com.

Please see the attachmen:
![invoice](https://user-images.githubusercontent.com/905799/33665569-a7b15690-da97-11e7-8691-2b8731578888.png)

Thank you,

David

**Comment by Spreeuw** [comment] 2017-12-06 14:17
@maralik this must be human error - the invoice is only generated when it is either attached to an email (which sounds like you have that set up correctly if it normally does not generate the invoice) or when a shop admin clicks the button to create the PDF manually. Perhaps a shop admin selects all orders and does a bulk export, including the failed order?

**Comment by maralik** [comment] 2017-12-06 15:38
Thank you for quick response - hard to say, we have from 221 failed orders generated 5 invoices and client tell us it's generated randomly without them.

When you do bulk Export as XLS the module will generate invoices for all selected orders?

**Comment by Spreeuw** [comment] 2017-12-06 16:20
I don't think any XLS exporter will generate invoices.
The only other thing I can think of is that you have set up invoices to be available for all statuses (PDF Invoices > Documents > Invoice > Allow My Account invoice download) and that the customer may have requested the PDF. Other than that, the plugin doesn't really do 'random'...

**Comment by Spreeuw** [comment] 2018-10-13 08:36
closing this issue as it seems this invoice was created manually and I can't reproduce. Note that the invoice date in your screenshots (november 13th) is several days from the date of the invoice (november 15th), which makes it more likely this was manual.
Please let me know if the issue appears again with steps to reproduce.

**Closed by Spreeuw** 2018-10-13 08:36 UTC
