### ISSUE TITLE
Orders not shown when updating to 2.0 beta 5

### ISSUE THREAD

**Issue by AdriOosterwijk** [wpovernight/woocommerce-pdf-invoices-packing-slips#22] opened 2017-06-17 07:30 UTC
Hi,
I downloaded the 2.0 beta 5 version and copied it into my plugins folder. I deactivated the 1.6.5 version and activated the new one. Next I tried to look at my orders and oops, no orders are shown. They must be somewhere because the number of orders is displayed and also the number of pages seems to be correct. There are just no orders displayed. Is it a flaw or am I doing something wrong here?

![schermafbeelding 2017-06-17 om 09 28 48](https://user-images.githubusercontent.com/10272269/27251085-6eae27ae-533f-11e7-8f21-9d89a271dd39.png)

Reverting back to 1.6.5 and all orders are displayed correctly.

Best wishes,

Adri

**Comment by Spreeuw** [comment] 2017-06-17 07:36
Thanks for reporting Adri! Do you see any errors in your error log? This may be related to the use of a filter applied to the invoice number. Can you temporarily turn off all your PDF invoice related filters to see if that helps?

**Comment by Spreeuw** [comment] 2017-06-17 07:37
Also, if you're using a custom template or any actions/filters using $wpo_wcpdf, please verify that 'Legacy Mode' is enabled in the Status tab of the settings.

**Comment by AdriOosterwijk** [comment] 2017-06-17 07:53
Yeah, I see an error when I turn on the debug mode in the WP-Config file. Here it is:

Fatal error: Uncaught Error: Call to undefined method WPO\WC\PDF_Invoices\Compatibility\WC_DateTime::set_utc_offset() in /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/documents/abstract-wcpdf-order-document.php:318 Stack trace: #0 /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/documents/abstract-wcpdf-order-document.php(283): WPO\WC\PDF_Invoices\Documents\Order_Document->set_date('2017-06-14 08:0...', Object(WC_Order)) #1 /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/documents/abstract-wcpdf-order-document.php(177): WPO\WC\PDF_Invoices\Documents\Order_Document->set_data(Array, Object(WC_Order)) #2 /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/documents/abstract-wcpdf-order-document.php(111): WPO\WC\PDF_Invoices\Documents\Order_Document->read_data(O in /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/documents/abstract-wcpdf-order-document.php on line 318

Legacy mode is on.

Deactivating the other PDF Invoice plugins is showing my orders again.
When I activate the plugins one by one gives me the error when activating the Pro plugin. With the Templates and Drobbox plugin activated the orders are showing fine.

**Comment by AdriOosterwijk** [comment] 2017-06-17 07:55
When trying to view a PDF invoice of an existing order I get an error also. See below:

Fatal error: Uncaught Exception: Call to undefined method WPO\WC\PDF_Invoices\Legacy\Legacy_Export::get_display_number() in /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/legacy/class-wcpdf-legacy-export.php:53 Stack trace: #0 /Users/adri/Documents/websites/htdocs/wp-content/themes/twentytwelve-child/functions.php(930): WPO\WC\PDF_Invoices\Legacy\Legacy_Export->__call('get_display_num...', Array) #1 /Users/adri/Documents/websites/htdocs/wp-includes/class-wp-hook.php(298): wpo_wcpdf_custom_filename('invoice-FCSP-00...', 'invoice', Array, 'download') #2 /Users/adri/Documents/websites/htdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters('invoice-FCSP-00...', Array) #3 /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/documents/class-wcpdf-invoice.php(106): apply_filters('wpo_wcpdf_filen...', 'invoice-FCSP-00...', 'invoice', Array, 'download') #4 /Users/adri/Documents/websites/htdocs/wp- in /Users/adri/Documents/websites/htdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips-2.0-beta-5/includes/legacy/class-wcpdf-legacy-export.php on line 53

**Comment by AdriOosterwijk** [comment] 2017-06-17 08:05
Next, deactivating 2.0 beta-5 and activating 1.6.5 again messes up my invoice layout.
For now I'm rolling back to my latest back-up.

**Comment by Spreeuw** [comment] 2017-06-17 08:09
The first error is occurring because the Pro and Free plugin share the compatibility library, which has been updated in the last version. But it can only load it once, and apparently it prefers the Pro one...

Can you test if changing this line:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/2.0-rewrite/woocommerce-pdf-invoices-packingslips.php#L51
to:
``` php
add_action( 'plugins_loaded', array( $this, 'load_classes' ), 9 );
```

fixes this issue?

The second fatal error is caused by your `wpo_wcpdf_custom_filename` filter, `get_display_number` no longer exists. I will add this to the legacy classes but I recommend updating this anyway to either:
```php
$document->get_invoice_number();
```
or 
```php
$order->get_order_number();
```

Can you show a screenshot of where your layout is messed up? Thanks!

**Comment by AdriOosterwijk** [comment] 2017-06-17 08:38
Changing line 51 did the trick for the first fatal error. The orders are listed like before.
Regarding the second one I'm struggling.....

below the filter I'm using (it's the "old" version which was working properly. I tried to change it with the snippets of code you gave but then it is starting to nag about unexpected breaks and so on.

`add_filter( 'wpo_wcpdf_filename', 'wpo_wcpdf_custom_filename', 10, 4 );
function wpo_wcpdf_custom_filename( $filename, $template_type, $order_ids, $context ) {
    global $wpo_wcpdf, $wpo_wcpdf_pro;
    $count = count($order_ids);
 
    switch ($template_type) {
        case 'invoice':
            $name = _n( '', 'invoices', $count, 'wpo_wcpdf' );
            $number = $wpo_wcpdf->export->get_display_number( $order_ids[0] );
            break;
        case 'packing-slip':
            $name = _n( '', 'packing-slips', $count, 'wpo_wcpdf' );
            $number = $wpo_wcpdf->export->order->get_order_number();
            break;
        case 'proforma':
            $name = _n( '', 'proforma-invoices', $count, 'wpo_wcpdf_pro' );
            $number = $wpo_wcpdf_pro->get_number('proforma');
            break;     
        case 'credit-note':
            $name = _n( '', 'credit-notes', $count, 'wpo_wcpdf_pro' );
            $number = $wpo_wcpdf_pro->get_number('credit-note');
            break;
        default:
            $name = $template_type;
            $number = $wpo_wcpdf->export->order->get_order_number();
            break;
    }
 
    if ( $count == 1 ) {
        $suffix = $number;
    } else {
        $suffix = date('Y-m-d'); // 2020-11-11
    }
 
    $filename = $name . '-' . $suffix . '.pdf';
 
    return $filename;
}
`
It is obvious that I'm doing something wrong here, but what?

Concerning the lay out
[FCSP-000415.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/1082431/FCSP-000415.pdf)

[invoice-FCSP-000414.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/1082435/invoice-FCSP-000414.pdf)

The first one is totally messed up as you can see (when reverted back to 1.6.5), the second one is produced after the the activation of 2.0 beta 5 and the first fatal error fix.

**Comment by AdriOosterwijk** [comment] 2017-06-17 08:40
I also get this notice for Dutch orders (using WPML).

Notice: $wpo_wcpdf->translations() is deprecated since version 2.0! Use WPO_WCPDF()->translations() instead. in /Users/adri/Documents/websites/htdocs/wp-includes/functions.php on line 3831

**Comment by Spreeuw** [comment] 2017-06-17 09:13
This should fix your issue with the filename filter for now:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/1c29f7b5437a088ff1ab6f82815e877bf4093162

The messed up layout appears to be font related, though I'm not sure (dompdf had a big update from 0.6 to 0.8). If you can share your complete template (zip) I can test it.

**Comment by Spreeuw** [comment] 2017-06-17 09:15
You can ignore the deprecation error, it will be gone when you update the pro extension.

**Comment by AdriOosterwijk** [comment] 2017-06-17 09:38
The notice will be ignored, the filename issue is solved and hereby my template files.
Of course I can, if needed, try to fix it with css. That must be not to difficult but it would be great if there are not a ton of questions from other users as well when the final 2.0 version is released.

[yourtemplate.zip](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/1082462/yourtemplate.zip)

For your reference I have added a saved PDF of an invoice as well so you will be able to see what it has to look like.
[FCSP-000411.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/1082464/FCSP-000411.pdf)

**Comment by Spreeuw** [comment] 2017-06-17 14:47
I can't reproduce the template issue, it's displaying fine on my site. I think the settings migration wasn't performed correctly, as explained in #23

**Comment by Spreeuw** [comment] 2017-06-26 18:22
Fixed with beta 7!

**Closed by Spreeuw** 2017-06-26 18:22 UTC
Labels: bug
